spring.application.name=auth-lobby-service
server.port=8081
spring.datasource.url=jdbc:h2:file:./data/authlobby;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

codenames.app.jwtSecret=YMPD3zJt7CXIZqG1Hr0wva67nZ5ntPOS
codenames.app.jwtExpirationMs=86400000